### ISSUE TITLE
java.lang.NoSuchMethodError when upgrading to guava 22.0

### ISSUE THREAD

**Issue by gotwalt** [Codearte/jfairy#86]
Using jfairy 0.5.7. The following exception is triggered by `Fairy.create()`.

```
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
	at io.codearte.jfairy.data.MapBasedDataMaster.getData(MapBasedDataMaster.java:87)
	at io.codearte.jfairy.data.MapBasedDataMaster.getString(MapBasedDataMaster.java:73)
	at io.codearte.jfairy.producer.text.TextProducerInternal.<init>(TextProducerInternal.java:51)
	at io.codearte.jfairy.producer.text.TextProducerInternal$$FastClassByGuice$$1d020c2d.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012)
	at com.google.inject.assistedinject.FactoryProvider2.invoke(FactoryProvider2.java:770)
	at io.codearte.jfairy.$Proxy50.createFairy(Unknown Source)
	at io.codearte.jfairy.Bootstrap.createFairy(Bootstrap.java:55)
	at io.codearte.jfairy.Bootstrap$Builder.build(Bootstrap.java:237)
	at io.codearte.jfairy.Bootstrap.create(Bootstrap.java:85)
	at io.codearte.jfairy.Fairy.create(Fairy.java:48)

**Comment by OlgaMaciaszek** [comment]
I have tried upgrading jFairy manually to that guava version and running the method and have not been able to reproduce the bug; guava 0.22 does have the following method signature: `com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)` . Please verify if there is no problem with transitive dependencies in your build setup, i.e. which guava version exactly is available in the classpath.

**Comment by benmccann** [comment]
jFairy is indeed compatible with Guava 22.0

(The one exception would be that Guava 22.0 is only compatible with Java 8, but if you tried to use it with Java 7 you would get a very different error and it would be unrelated to your usage of jFairy)
